### ISSUE TITLE
customfeeds.conf points to the wrong adress

### ISSUE THREAD

**Issue by Meierhans2** [Firmware-routers/Easybox-904-xDSL#2]
For SMP I changed it to, and it works now:

src/gz easybox904_core https://raw.githubusercontent.com/Firmware-routers/Easybox-904-xDSL/main/Repository/EB904xDSL/SMP/v1/core
src/gz easybox904_easybox904 https://raw.githubusercontent.com/Firmware-routers/Easybox-904-xDSL/main/Repository/EB904xDSL/SMP/v1/easybox904

I must admit, I am a bit confused by the 3 different 904x repo´s in general:
 
https://github.com/zuzia-dev/Easybox-904xDSL
https://github.com/zuzia-dev/Easybox-904xDSL-repo-source
https://github.com/Firmware-routers/Easybox-904-xDSL

**Comment by zuzia-dev** [comment]
Hi @Meierhans2 
The problem has been resolved in the new version of OpenWrt 21.02.7:
VPE: https://github.com/zuzia-dev/Easybox-904xDSL-repo-source/blob/main/Firmware/VPE/v2/openwrt-lantiq-xrx200-arcadyan_vgv952cjw33-e-ir-vpe-squashfs-sysupgrade.bin
SMP: https://github.com/zuzia-dev/Easybox-904xDSL-repo-source/blob/main/Firmware/SMP/v2/openwrt-lantiq-xrx200-arcadyan_vgv952cjw33-e-ir-smp-squashfs-sysupgrade.bin
The correct repository is currently only this one: https://github.com/zuzia-dev/Easybox-904xDSL-repo-source
The others are for testing.
